services:
  db:
    image: postgres:15
    container_name: fingerprint_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fingerprintdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: fingerprint_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/fingerprintdb
      SECUGEN_SDK_PATH: ${SECUGEN_SDK_PATH:-}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # for live code sync
      - backend_venv:/app/.venv  # preserve dependencies for remote interpreter

  frontend:
    build: ./frontend
    container_name: fingerprint_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/usr/src/app:delegated
      - frontend_node_modules:/usr/src/app/node_modules
    command: ["yarn", "dev"]
    depends_on:
      - backend

volumes:
  db_data:
  frontend_node_modules:
  backend_venv:
